### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Itrustsecurity** [tharyckgusmao/integrada.minhabiblioteca.com.br#9]
Hi All

Thanks for the tool, 
I've tried to install it but i receive this error at the end 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/fsevents/node_modules/wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/root/integrada.minhabiblioteca.com.br/node_modules/fsevents/node_modules/wrappy' -> '/root/integrada.minhabiblioteca.com.br/node_modules/fsevents/node_modules/.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/fsevents/node_modules/yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/root/integrada.minhabiblioteca.com.br/node_modules/fsevents/node_modules/yallist' -> '/root/integrada.minhabiblioteca.com.br/node_modules/fsevents/node_modules/.yallist.DELETE'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-18T05_22_44_759Z-debug.log
root@oceans:~/integrada.minhabiblioteca.com.br# 

Please find attached the installation log file
Any help ?
Thanks

**Comment by Itrustsecurity** [comment]
Please find attached the installation log file

**Comment by Itrustsecurity** [comment]
This error is diplayed during the compilation : npm run build

Time: 24182ms
                                Asset       Size  Chunks                    Chunk Names
 71394c0c7ad6c1e7d5c77e8ac292fba5.eot    58.7 kB          [emitted]         
 c45f7de008ab976a8e817e3c0e5095ca.svg     164 kB          [emitted]         
 01798bc13e33afc36a52f2826638d386.ttf    58.5 kB          [emitted]         
b38ef310874bdd008ac14ef3db939032.woff    58.6 kB          [emitted]         
     main-93ae841d3a091a01150d.min.js    10.4 MB       0  [emitted]  [big]  main
    main-93ae841d3a091a01150d.min.css    7.34 kB       0  [emitted]         main
                           index.html  567 bytes          [emitted]         
   [8] ./~/react/react.js 56 bytes {0} [built]
       [] -> factory:197ms building:280ms = 477ms
  [49] ./~/react-router/es/RouteUtils.js 2.43 kB {0} [built]
       [] -> factory:174ms building:148ms dependencies:397ms = 719ms
  [76] ./~/react-router/es/PatternUtils.js 7.34 kB {0} [built]
       [] -> factory:175ms building:178ms dependencies:826ms = 1179ms
 [152] ./~/react-router/es/index.js 1.46 kB {0} [built]
       [] -> factory:212ms building:355ms = 567ms
 [243] ./~/react-redux/es/index.js 229 bytes {0} [built]
       [] -> factory:200ms building:284ms = 484ms
 [245] ./~/react-router-redux/lib/index.js 1.97 kB {0} [built]
       [] -> factory:212ms building:365ms = 577ms
 [475] ./app/app.js 1.69 kB {0} [built]
       [] -> factory:43ms building:868ms = 911ms
 [495] ./app/containers/Root.js 2.54 kB {0} [built]
       [] -> factory:15ms building:150ms dependencies:47ms = 212ms
 [499] ./app/routes/routes.js 720 bytes {0} [built]
       [] -> factory:14ms building:46ms dependencies:152ms = 212ms
 [501] ./app/store/configureStore.js 188 bytes {0} [built]
       [] -> factory:14ms building:13ms = 27ms
 [970] ./~/react-dom/index.js 59 bytes {0} [built]
       [] -> factory:198ms building:281ms = 479ms
[1034] ./~/react-hot-loader/index.js 40 bytes {0} [built]
       [] -> factory:197ms building:280ms = 477ms
[1128] ./~/style-loader!./~/css-loader!./app/assets/styles/fonts.css 1.02 kB {0} [built]
       [] -> factory:207ms building:2ms dependencies:277ms = 486ms
[1129] ./~/style-loader!./~/css-loader!./app/assets/styles/global.css 1.02 kB {0} [built]
       [] -> factory:203ms building:3ms = 206ms
[1161] multi ./app/app 28 bytes {0} [built]
        factory:0ms building:1ms = 1ms
    + 1152 hidden modules

ERROR in main-93ae841d3a091a01150d.min.js from UglifyJs
Name expected [main-93ae841d3a091a01150d.min.js:4714,6]
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 541 kB {0} [built]
           [] -> factory:2ms building:672ms = 674ms
       [1] ./~/html-webpack-plugin/lib/loader.js!./app/index.tpl.html 795 bytes {0} [built]
            factory:23ms building:21ms = 44ms
       [2] (webpack)/buildin/module.js 517 bytes {0} [built]
           [] -> factory:216ms building:153ms = 369ms
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
           [] -> factory:1ms building:1ms = 2ms
       [1] ./~/css-loader?sourceMap&modules&importLoaders=1&localIdentName=__[hash:base64:5]!./~/postcss-loader/lib!./app/view/home/styles/styles.css 3.96 kB {0} [built]
            factory:16ms building:30ms = 46ms
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
           [] -> factory:0ms building:2ms = 2ms
        + 1 hidden modules
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
           [] -> factory:1ms building:2ms = 3ms
        + 1 hidden modules
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
           [] -> factory:1ms building:1ms = 2ms
        + 1 hidden modules
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
           [] -> factory:1ms building:1ms = 2ms
        + 1 hidden modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! integradaBibliotecaV2@2.0.0 build: `rimraf dist && webpack --config ./webpack.config.prod.js --progress --profile --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the integradaBibliotecaV2@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-18T08_15_00_861Z-debug.log
root@oceans:~/integrada.minhabiblioteca.com.br#

**Comment by Itrustsecurity** [comment]
root@oceans:~/integrada.minhabiblioteca.com.br# npm run ele 

> integradaBibliotecaV2@2.0.0 ele /root/integrada.minhabiblioteca.com.br
> NODE_ENV=development electron ./electron/init.js 

sh: 1: electron: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! integradaBibliotecaV2@2.0.0 ele: `NODE_ENV=development electron ./electron/init.js `
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the integradaBibliotecaV2@2.0.0 ele script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-18T08_30_37_889Z-debug.log
root@oceans:~/integrada.minhabiblioteca.com.br# cat  /root/.npm/_logs/2020-03-18T08_30_37_889Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'ele' ]
2 info using npm@6.13.7
3 info using node@v14.0.0-pre
4 verbose run-script [ 'preele', 'ele', 'postele' ]
5 info lifecycle integradaBibliotecaV2@2.0.0~preele: integradaBibliotecaV2@2.0.0
6 info lifecycle integradaBibliotecaV2@2.0.0~ele: integradaBibliotecaV2@2.0.0
7 verbose lifecycle integradaBibliotecaV2@2.0.0~ele: unsafe-perm in lifecycle true
8 verbose lifecycle integradaBibliotecaV2@2.0.0~ele: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/integrada.minhabiblioteca.com.br/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle integradaBibliotecaV2@2.0.0~ele: CWD: /root/integrada.minhabiblioteca.com.br
10 silly lifecycle integradaBibliotecaV2@2.0.0~ele: Args: [ '-c', 'NODE_ENV=development electron ./electron/init.js ' ]
11 info lifecycle integradaBibliotecaV2@2.0.0~ele: Failed to exec ele script
12 verbose stack Error: integradaBibliotecaV2@2.0.0 ele: `NODE_ENV=development electron ./electron/init.js `
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:316:20)
12 verbose stack     at maybeClose (internal/child_process.js:1051:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid integradaBibliotecaV2@2.0.0
14 verbose cwd /root/integrada.minhabiblioteca.com.br
15 verbose Linux 4.9.0-kali3-amd64
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ele"
17 verbose node v14.0.0-pre
18 verbose npm  v6.13.7
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error integradaBibliotecaV2@2.0.0 ele: `NODE_ENV=development electron ./electron/init.js `
23 error spawn ENOENT
24 error Failed at the integradaBibliotecaV2@2.0.0 ele script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
root@oceans:~/integrada.minhabiblioteca.com.br#
